# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Percy
email:
description: > # The friendly chocolate printer made by makersnz-wgtn meetup at Fab Lab Wgtn
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://http://fablabwgtn.github.io/Percy" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
